server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service # \uB77C\uC6B0\uD305\uD560 \uC11C\uBE44\uC2A4\uC758 ID\uB97C \uC124\uC815\uD55C\uB2E4.
          uri: lb://user-service # lb\uB294 load balancer\uC758 \uC57D\uC790\uB85C, Eureka Server\uC5D0 \uB4F1\uB85D\uB41C \uC11C\uBE44\uC2A4\uB4E4 \uC911\uC5D0\uC11C user-service\uB97C \uCC3E\uC544\uC11C \uB77C\uC6B0\uD305\uD55C\uB2E4.
          predicates:
            - Path=/user-service/** # /user-service/**\uB85C \uB4E4\uC5B4\uC624\uB294 \uC694\uCCAD\uC744 \uB77C\uC6B0\uD305\uD55C\uB2E4.
          filters:
#            - AddRequestHeader=user-request, user-request-header
#            - AddResponseHeader=user-response, user-response-header
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging Filter
                preLogger: true
                postLogger: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Default Filter
            preLogger: true
            postLogger: true