eureka:
  client:
    service-url:
      defaultZone: http://ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com:8761/eureka
  instance:
    hostname: ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com
    home-page-url: http://ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com
    status-page-url: http://ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com/actuator/info
    health-check-url: http://ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com/actuator/healthdi