
server:
  port: 0 # \uAC19\uC740 \uC11C\uBE44\uC2A4\uB97C \uC5EC\uB7EC\uAC1C \uB744\uC6B8 \uB54C \uCDA9\uB3CC\uC744 \uBC29\uC9C0\uD558\uAE30 \uC704\uD574 \uC784\uC758\uC758 \uD3EC\uD2B8\uB85C \uC124\uC815

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} # \uC11C\uBE44\uC2A4 \uC778\uC2A4\uD134\uC2A4 ID
  client:
    register-with-eureka: true # Discovery Server\uC5D0 \uB4F1\uB85D
    fetch-registry: true # Discovery Server\uC5D0 \uB4F1\uB85D\uB41C \uC11C\uBE44\uC2A4 \uC815\uBCF4\uB97C \uB85C\uCEEC \uCE90\uC2DC\uC5D0 \uB4F1\uB85D
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # Discovery Server\uC758 \uB4F1\uB85D \uC8FC\uC18C