eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com

greeting:
  message: Hello fucking,,, # application.yml에 설정된 greeting.message를 사용한다.