
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:sample;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Eureka에 등록될 서비스의 인스턴스 ID를 설정한다.
    hostname: ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com

  client:
    service-url:
      defaultZone: http://ss-dev-alb-311095464.ap-northeast-2.elb.amazonaws.com:8761/eureka
