# Eureka Server Configuration
server:
  port: 8761

# Eureka display name
spring:
  application:
    name: discoveryservice

eureka:
    client:
        register-with-eureka: false # 해당 프로젝트는 Discovery Server이므로, Eureka Server에 등록하지 않는다.
        fetch-registry: false # Eureka Server에 등록된 서비스들의 정보를 가져오지 않는다.